# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JofMp7HYgEok0e9J1ja_T5pckHcNjK6d
"""

9

10 + 5

(10+5)*3

10+5*3

10/5   # Float Division

10//5  # Int Division